apisix:
  node_listen: 9080
  enable_admin: true
  allow_admin:
    - 0.0.0.0/0
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

etcd:
  host:
    - "http://nexlify-etcd:2379"
