services:
  nexlify-nginx:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - redis
      - nexlify-fallback
      - auth-service
      - order-service
    networks:
      - nexlify-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - nexlify-net

  nexlify-fallback:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    dns:
         - 8.8.8.8
         - 1.1.1.1
    environment:
      - JWT_SECRET=your-jwt-secret
      - REFRESH_TOKEN_SECRET=your-refresh-token-secret
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - auth-service
      - order-service

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./gateway/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - nexlify-net

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    dns:
          - 8.8.8.8
          - 1.1.1.1
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/auth
      - JWT_SECRET=your-jwt-secret
      - REFRESH_TOKEN_SECRET=your-refresh-token-secret

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    dns:
          - 8.8.8.8
          - 1.1.1.1
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/orders

networks:
  nexlify-net:
    driver: bridge
