apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /hello
        routeAction:
          single:
            upstream:
              name: httpbin
              namespace: gloo-system
